# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [70]:
import numpy as np
import pandas as pd

#### 2. Print your NumPy version.

In [6]:
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [15]:
# Method 1
a=np.random.random((2,3,5))
a

array([[[0.40563558, 0.89994383, 0.19391278, 0.53231413, 0.88575685],
        [0.22433487, 0.30041791, 0.68825466, 0.52054407, 0.75508985],
        [0.74062833, 0.81952328, 0.41391538, 0.72448621, 0.03196963]],

       [[0.39861542, 0.37319981, 0.61460692, 0.19019899, 0.30249002],
        [0.78233796, 0.84430248, 0.94938266, 0.02677076, 0.97027389],
        [0.756992  , 0.08449039, 0.58271806, 0.01315351, 0.22028175]]])

In [10]:
# Method 2
np.random.rand(2,3,5)

array([[[0.57355647, 0.77647017, 0.64418718, 0.43651099, 0.58319608],
        [0.58528643, 0.24950094, 0.22539113, 0.03511453, 0.67658369],
        [0.90391355, 0.84660799, 0.44681464, 0.58539968, 0.63512263]],

       [[0.78401171, 0.62171973, 0.7121172 , 0.92944477, 0.11607797],
        [0.19081695, 0.81197355, 0.38063649, 0.64088341, 0.97578866],
        [0.23982704, 0.15431867, 0.6229341 , 0.1435821 , 0.47764982]]])

In [13]:
# Method 3
np.random.random_sample((2,3,5))

array([[[0.04889819, 0.91192401, 0.77007789, 0.38271482, 0.87347801],
        [0.61671691, 0.70078638, 0.35138127, 0.92799599, 0.45854938],
        [0.61719236, 0.52706272, 0.89532337, 0.26202984, 0.91641573]],

       [[0.42998119, 0.34079615, 0.2259418 , 0.97242214, 0.14952475],
        [0.8399454 , 0.91238409, 0.38042091, 0.53122311, 0.76379062],
        [0.18374851, 0.58805127, 0.03425395, 0.81221432, 0.99756667]]])

#### 4. Print *a*.


In [16]:
display(a)

array([[[0.40563558, 0.89994383, 0.19391278, 0.53231413, 0.88575685],
        [0.22433487, 0.30041791, 0.68825466, 0.52054407, 0.75508985],
        [0.74062833, 0.81952328, 0.41391538, 0.72448621, 0.03196963]],

       [[0.39861542, 0.37319981, 0.61460692, 0.19019899, 0.30249002],
        [0.78233796, 0.84430248, 0.94938266, 0.02677076, 0.97027389],
        [0.756992  , 0.08449039, 0.58271806, 0.01315351, 0.22028175]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [24]:
b=np.array([[[1,1,1]]*2]*5)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [25]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [27]:
a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [29]:
a+b
""" shapes are different.(2,3,5)vs. (5,2,3)"""

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [130]:
c=b.transpose(1,2,0) # change axes (5,2,3 index from 0,1,2 to index 1,2,0)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [131]:
d=a+c
display(d)
""" shapes are the sames.(2,3,5)"""

array([[[1.40563558, 1.89994383, 1.19391278, 1.53231413, 1.88575685],
        [1.22433487, 1.30041791, 1.68825466, 1.52054407, 1.75508985],
        [1.74062833, 1.81952328, 1.41391538, 1.72448621, 1.03196963]],

       [[1.39861542, 1.37319981, 1.61460692, 1.19019899, 1.30249002],
        [1.78233796, 1.84430248, 1.94938266, 1.02677076, 1.97027389],
        [1.756992  , 1.08449039, 1.58271806, 1.01315351, 1.22028175]]])

' shapes are the sames.(2,3,5)'

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [65]:
a,d


(array([[[0.40563558, 0.89994383, 0.19391278, 0.53231413, 0.88575685],
         [0.22433487, 0.30041791, 0.68825466, 0.52054407, 0.75508985],
         [0.74062833, 0.81952328, 0.41391538, 0.72448621, 0.03196963]],
 
        [[0.39861542, 0.37319981, 0.61460692, 0.19019899, 0.30249002],
         [0.78233796, 0.84430248, 0.94938266, 0.02677076, 0.97027389],
         [0.756992  , 0.08449039, 0.58271806, 0.01315351, 0.22028175]]]),
 array([[[1.40563558, 1.89994383, 1.19391278, 1.53231413, 1.88575685],
         [1.22433487, 1.30041791, 1.68825466, 1.52054407, 1.75508985],
         [1.74062833, 1.81952328, 1.41391538, 1.72448621, 1.03196963]],
 
        [[1.39861542, 1.37319981, 1.61460692, 1.19019899, 1.30249002],
         [1.78233796, 1.84430248, 1.94938266, 1.02677076, 1.97027389],
         [1.756992  , 1.08449039, 1.58271806, 1.01315351, 1.22028175]]]))

In [43]:
d==1+a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [47]:
#multiplication of element
e=np.multiply(a,c)
e

array([[[0.40563558, 0.89994383, 0.19391278, 0.53231413, 0.88575685],
        [0.22433487, 0.30041791, 0.68825466, 0.52054407, 0.75508985],
        [0.74062833, 0.81952328, 0.41391538, 0.72448621, 0.03196963]],

       [[0.39861542, 0.37319981, 0.61460692, 0.19019899, 0.30249002],
        [0.78233796, 0.84430248, 0.94938266, 0.02677076, 0.97027389],
        [0.756992  , 0.08449039, 0.58271806, 0.01315351, 0.22028175]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [49]:
a==e
"""the multiplication is element wise so it is equivalent 1*a"""

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [66]:
d_max=d.max()
d_min=d.min()
d_mean=d.mean()
print(d_max,d_min,d_mean)

1.9702738878468207 1.0131535068193438 1.5082180650774186


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [57]:
f=np.empty([2,3,5])
f

array([[[0.40563558, 0.89994383, 0.19391278, 0.53231413, 0.88575685],
        [0.22433487, 0.30041791, 0.68825466, 0.52054407, 0.75508985],
        [0.74062833, 0.81952328, 0.41391538, 0.72448621, 0.03196963]],

       [[0.39861542, 0.37319981, 0.61460692, 0.19019899, 0.30249002],
        [0.78233796, 0.84430248, 0.94938266, 0.02677076, 0.97027389],
        [0.756992  , 0.08449039, 0.58271806, 0.01315351, 0.22028175]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [59]:
d.shape

(2, 3, 5)

In [67]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i,j,k]>d_min and d[i,j,k]<d_mean:
                f[i,j,k]=25
            elif d[i,j,k]<d_max and d[i,j,k]>d_mean:
                f[i,j,k]=75
            elif d[i,j,k]==d_mean:
                f[i,j,k]=50
            elif d[i,j,k]==d_min:
                f[i,j,k]=0
            else:
                f[i,j,k]=100
f

array([[[ 25.,  75.,  25.,  75.,  75.],
        [ 25.,  25.,  75.,  75.,  75.],
        [ 75.,  75.,  25.,  75.,  25.]],

       [[ 25.,  25.,  75.,  25.,  25.],
        [ 75.,  75.,  75.,  25., 100.],
        [ 75.,  25.,  75.,   0.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [68]:
d,f

(array([[[1.40563558, 1.89994383, 1.19391278, 1.53231413, 1.88575685],
         [1.22433487, 1.30041791, 1.68825466, 1.52054407, 1.75508985],
         [1.74062833, 1.81952328, 1.41391538, 1.72448621, 1.03196963]],
 
        [[1.39861542, 1.37319981, 1.61460692, 1.19019899, 1.30249002],
         [1.78233796, 1.84430248, 1.94938266, 1.02677076, 1.97027389],
         [1.756992  , 1.08449039, 1.58271806, 1.01315351, 1.22028175]]]),
 array([[[ 25.,  75.,  25.,  75.,  75.],
         [ 25.,  25.,  75.,  75.,  75.],
         [ 75.,  75.,  25.,  75.,  25.]],
 
        [[ 25.,  25.,  75.,  25.,  25.],
         [ 75.,  75.,  75.,  25., 100.],
         [ 75.,  25.,  75.,   0.,  25.]]]))

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [128]:
def change_val(x):
    if x==0:
        x='A'
    elif x==25:
        x='B'
    elif x==50:
        x='C'
    elif x==75:
        x='D'
    else :
        x='E'
    return x




In [132]:
vfunc = np.vectorize( change_val) 

vfunc(f)

array([[['B', 'D', 'B', 'D', 'D'],
        ['B', 'B', 'D', 'D', 'D'],
        ['D', 'D', 'B', 'D', 'B']],

       [['B', 'B', 'D', 'B', 'B'],
        ['D', 'D', 'D', 'B', 'E'],
        ['D', 'B', 'D', 'A', 'B']]], dtype='<U1')